#include "ISO639_2.h"
#include <map>
#include <string>

static const std::map<std::string,std::string> langs = {
	std::make_pair<std::string,std::string>("aar", "Afar"),
	std::make_pair<std::string,std::string>("abk", "Abkhazian"),
	std::make_pair<std::string,std::string>("ace", "Achinese"),
	std::make_pair<std::string,std::string>("ach", "Acoli"),
	std::make_pair<std::string,std::string>("ada", "Adangme"),
	std::make_pair<std::string,std::string>("ady", "Adyghe; Adygei"),
	std::make_pair<std::string,std::string>("afa", "Afro-Asiatic languages"),
	std::make_pair<std::string,std::string>("afh", "Afrihili"),
	std::make_pair<std::string,std::string>("afr", "Afrikaans"),
	std::make_pair<std::string,std::string>("ain", "Ainu"),
	std::make_pair<std::string,std::string>("aka", "Akan"),
	std::make_pair<std::string,std::string>("akk", "Akkadian"),
	std::make_pair<std::string,std::string>("alb", "Albanian"),
	std::make_pair<std::string,std::string>("sqi", "Albanian"),
	std::make_pair<std::string,std::string>("ale", "Aleut"),
	std::make_pair<std::string,std::string>("alg", "Algonquian languages"),
	std::make_pair<std::string,std::string>("alt", "Southern Altai"),
	std::make_pair<std::string,std::string>("amh", "Amharic"),
	std::make_pair<std::string,std::string>("ang", "Old English (450-1100)"),
	std::make_pair<std::string,std::string>("anp", "Angika"),
	std::make_pair<std::string,std::string>("apa", "Apache languages"),
	std::make_pair<std::string,std::string>("ara", "Arabic"),
	std::make_pair<std::string,std::string>("arc", "Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)"),
	std::make_pair<std::string,std::string>("arg", "Aragonese"),
	std::make_pair<std::string,std::string>("arm", "Armenian"),
	std::make_pair<std::string,std::string>("hye", "Armenian"),
	std::make_pair<std::string,std::string>("arn", "Mapudungun; Mapuche"),
	std::make_pair<std::string,std::string>("arp", "Arapaho"),
	std::make_pair<std::string,std::string>("art", "Artificial languages"),
	std::make_pair<std::string,std::string>("arw", "Arawak"),
	std::make_pair<std::string,std::string>("asm", "Assamese"),
	std::make_pair<std::string,std::string>("ast", "Asturian; Bable; Leonese; Asturleonese"),
	std::make_pair<std::string,std::string>("ath", "Athapascan languages"),
	std::make_pair<std::string,std::string>("aus", "Australian languages"),
	std::make_pair<std::string,std::string>("ava", "Avaric"),
	std::make_pair<std::string,std::string>("ave", "Avestan"),
	std::make_pair<std::string,std::string>("awa", "Awadhi"),
	std::make_pair<std::string,std::string>("aym", "Aymara"),
	std::make_pair<std::string,std::string>("aze", "Azerbaijani"),
	std::make_pair<std::string,std::string>("bad", "Banda languages"),
	std::make_pair<std::string,std::string>("bai", "Bamileke languages"),
	std::make_pair<std::string,std::string>("bak", "Bashkir"),
	std::make_pair<std::string,std::string>("bal", "Baluchi"),
	std::make_pair<std::string,std::string>("bam", "Bambara"),
	std::make_pair<std::string,std::string>("ban", "Balinese"),
	std::make_pair<std::string,std::string>("baq", "Basque"),
	std::make_pair<std::string,std::string>("eus", "Basque"),
	std::make_pair<std::string,std::string>("bas", "Basa"),
	std::make_pair<std::string,std::string>("bat", "Baltic languages"),
	std::make_pair<std::string,std::string>("bej", "Beja; Bedawiyet"),
	std::make_pair<std::string,std::string>("bel", "Belarusian"),
	std::make_pair<std::string,std::string>("bem", "Bemba"),
	std::make_pair<std::string,std::string>("ben", "Bengali"),
	std::make_pair<std::string,std::string>("ber", "Berber languages"),
	std::make_pair<std::string,std::string>("bho", "Bhojpuri"),
	std::make_pair<std::string,std::string>("bih", "Bihari languages"),
	std::make_pair<std::string,std::string>("bik", "Bikol"),
	std::make_pair<std::string,std::string>("bin", "Bini; Edo"),
	std::make_pair<std::string,std::string>("bis", "Bislama"),
	std::make_pair<std::string,std::string>("bla", "Siksika"),
	std::make_pair<std::string,std::string>("bnt", "Bantu languages"),
	std::make_pair<std::string,std::string>("bod", "Tibetan"),
	std::make_pair<std::string,std::string>("tib", "Tibetan"),
	std::make_pair<std::string,std::string>("bos", "Bosnian"),
	std::make_pair<std::string,std::string>("bra", "Braj"),
	std::make_pair<std::string,std::string>("bre", "Breton"),
	std::make_pair<std::string,std::string>("btk", "Batak languages"),
	std::make_pair<std::string,std::string>("bua", "Buriat"),
	std::make_pair<std::string,std::string>("bug", "Buginese"),
	std::make_pair<std::string,std::string>("bul", "Bulgarian"),
	std::make_pair<std::string,std::string>("bur", "Burmese"),
	std::make_pair<std::string,std::string>("mya", "Burmese"),
	std::make_pair<std::string,std::string>("byn", "Bilin; Blin"),
	std::make_pair<std::string,std::string>("cad", "Caddo"),
	std::make_pair<std::string,std::string>("cai", "Central American Indian languages"),
	std::make_pair<std::string,std::string>("car", "Galibi Carib"),
	std::make_pair<std::string,std::string>("cat", "Catalan; Valencian"),
	std::make_pair<std::string,std::string>("cau", "Caucasian languages"),
	std::make_pair<std::string,std::string>("ceb", "Cebuano"),
	std::make_pair<std::string,std::string>("cel", "Celtic languages"),
	std::make_pair<std::string,std::string>("ces", "Czech"),
	std::make_pair<std::string,std::string>("cze", "Czech"),
	std::make_pair<std::string,std::string>("cha", "Chamorro"),
	std::make_pair<std::string,std::string>("chb", "Chibcha"),
	std::make_pair<std::string,std::string>("che", "Chechen"),
	std::make_pair<std::string,std::string>("chg", "Chagatai"),
	std::make_pair<std::string,std::string>("chi", "Chinese"),
	std::make_pair<std::string,std::string>("zho", "Chinese"),
	std::make_pair<std::string,std::string>("chk", "Chuukese"),
	std::make_pair<std::string,std::string>("chm", "Mari"),
	std::make_pair<std::string,std::string>("chn", "Chinook jargon"),
	std::make_pair<std::string,std::string>("cho", "Choctaw"),
	std::make_pair<std::string,std::string>("chp", "Chipewyan; Dene Suline"),
	std::make_pair<std::string,std::string>("chr", "Cherokee"),
	std::make_pair<std::string,std::string>("chu", "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic"),
	std::make_pair<std::string,std::string>("chv", "Chuvash"),
	std::make_pair<std::string,std::string>("chy", "Cheyenne"),
	std::make_pair<std::string,std::string>("cmc", "Chamic languages"),
	std::make_pair<std::string,std::string>("cop", "Coptic"),
	std::make_pair<std::string,std::string>("cor", "Cornish"),
	std::make_pair<std::string,std::string>("cos", "Corsican"),
	std::make_pair<std::string,std::string>("cpe", "English-based Creoles and pidgins"),
	std::make_pair<std::string,std::string>("cpf", "French-based Creoles and pidgins"),
	std::make_pair<std::string,std::string>("cpp", "Portuguese-based Creoles and pidgins"),
	std::make_pair<std::string,std::string>("cre", "Cree"),
	std::make_pair<std::string,std::string>("crh", "Crimean Tatar; Crimean Turkish"),
	std::make_pair<std::string,std::string>("crp", "Creoles and pidgins"),
	std::make_pair<std::string,std::string>("csb", "Kashubian"),
	std::make_pair<std::string,std::string>("cus", "Cushitic languages"),
	std::make_pair<std::string,std::string>("cym", "Welsh"),
	std::make_pair<std::string,std::string>("wel", "Welsh"),
	std::make_pair<std::string,std::string>("dak", "Dakota"),
	std::make_pair<std::string,std::string>("dan", "Danish"),
	std::make_pair<std::string,std::string>("dar", "Dargwa"),
	std::make_pair<std::string,std::string>("day", "Land Dayak languages"),
	std::make_pair<std::string,std::string>("del", "Delaware"),
	std::make_pair<std::string,std::string>("den", "Slave (Athapascan)"),
	std::make_pair<std::string,std::string>("deu", "German"),
	std::make_pair<std::string,std::string>("ger", "German"),
	std::make_pair<std::string,std::string>("dgr", "Dogrib"),
	std::make_pair<std::string,std::string>("din", "Dinka"),
	std::make_pair<std::string,std::string>("div", "Divehi; Dhivehi; Maldivian"),
	std::make_pair<std::string,std::string>("doi", "Dogri"),
	std::make_pair<std::string,std::string>("dra", "Dravidian languages"),
	std::make_pair<std::string,std::string>("dsb", "Lower Sorbian"),
	std::make_pair<std::string,std::string>("dua", "Duala"),
	std::make_pair<std::string,std::string>("dum", "Middle Dutch (1050-1350)"),
	std::make_pair<std::string,std::string>("dut", "Dutch; Flemish"),
	std::make_pair<std::string,std::string>("nld", "Dutch; Flemish"),
	std::make_pair<std::string,std::string>("dyu", "Dyula"),
	std::make_pair<std::string,std::string>("dzo", "Dzongkha"),
	std::make_pair<std::string,std::string>("efi", "Efik"),
	std::make_pair<std::string,std::string>("egy", "Egyptian (Ancient)"),
	std::make_pair<std::string,std::string>("eka", "Ekajuk"),
	std::make_pair<std::string,std::string>("ell", "Modern Greek (1453-)"),
	std::make_pair<std::string,std::string>("gre", "Modern Greek (1453-)"),
	std::make_pair<std::string,std::string>("elx", "Elamite"),
	std::make_pair<std::string,std::string>("eng", "English"),
	std::make_pair<std::string,std::string>("enm", "Middle English (1100-1500)"),
	std::make_pair<std::string,std::string>("epo", "Esperanto"),
	std::make_pair<std::string,std::string>("est", "Estonian"),
	std::make_pair<std::string,std::string>("ewe", "Ewe"),
	std::make_pair<std::string,std::string>("ewo", "Ewondo"),
	std::make_pair<std::string,std::string>("fan", "Fang"),
	std::make_pair<std::string,std::string>("fao", "Faroese"),
	std::make_pair<std::string,std::string>("fas", "Persian"),
	std::make_pair<std::string,std::string>("per", "Persian"),
	std::make_pair<std::string,std::string>("fat", "Fanti"),
	std::make_pair<std::string,std::string>("fij", "Fijian"),
	std::make_pair<std::string,std::string>("fil", "Filipino; Pilipino"),
	std::make_pair<std::string,std::string>("fin", "Finnish"),
	std::make_pair<std::string,std::string>("fiu", "Finno-Ugrian languages"),
	std::make_pair<std::string,std::string>("fon", "Fon"),
	std::make_pair<std::string,std::string>("fra", "French"),
	std::make_pair<std::string,std::string>("fre", "French"),
	std::make_pair<std::string,std::string>("frm", "Middle French (1400-1600)"),
	std::make_pair<std::string,std::string>("fro", "Old French (842-1400)"),
	std::make_pair<std::string,std::string>("frr", "Northern Frisian"),
	std::make_pair<std::string,std::string>("frs", "Eastern Frisian"),
	std::make_pair<std::string,std::string>("fry", "Western Frisian"),
	std::make_pair<std::string,std::string>("ful", "Fulah"),
	std::make_pair<std::string,std::string>("fur", "Friulian"),
	std::make_pair<std::string,std::string>("gaa", "Ga"),
	std::make_pair<std::string,std::string>("gay", "Gayo"),
	std::make_pair<std::string,std::string>("gba", "Gbaya"),
	std::make_pair<std::string,std::string>("gem", "Germanic languages"),
	std::make_pair<std::string,std::string>("geo", "Georgian"),
	std::make_pair<std::string,std::string>("kat", "Georgian"),
	std::make_pair<std::string,std::string>("gez", "Ge'ez"),
	std::make_pair<std::string,std::string>("gil", "Gilbertese"),
	std::make_pair<std::string,std::string>("gla", "Gaelic; Scottish Gaelic"),
	std::make_pair<std::string,std::string>("gle", "Irish"),
	std::make_pair<std::string,std::string>("glg", "Galician"),
	std::make_pair<std::string,std::string>("glv", "Manx"),
	std::make_pair<std::string,std::string>("gmh", "Middle High German (1050-1500)"),
	std::make_pair<std::string,std::string>("goh", "Old High German (750-1050)"),
	std::make_pair<std::string,std::string>("gon", "Gondi"),
	std::make_pair<std::string,std::string>("gor", "Gorontalo"),
	std::make_pair<std::string,std::string>("got", "Gothic"),
	std::make_pair<std::string,std::string>("grb", "Grebo"),
	std::make_pair<std::string,std::string>("grc", "Ancient Greek"),
	std::make_pair<std::string,std::string>("gre", "Greek"),
	std::make_pair<std::string,std::string>("grn", "Guarani"),
	std::make_pair<std::string,std::string>("gsw", "Swiss German; Alemannic; Alsatian"),
	std::make_pair<std::string,std::string>("guj", "Gujarati"),
	std::make_pair<std::string,std::string>("gwi", "Gwich'in"),
	std::make_pair<std::string,std::string>("hai", "Haida"),
	std::make_pair<std::string,std::string>("hat", "Haitian; Haitian Creole"),
	std::make_pair<std::string,std::string>("hau", "Hausa"),
	std::make_pair<std::string,std::string>("haw", "Hawaiian"),
	std::make_pair<std::string,std::string>("heb", "Hebrew"),
	std::make_pair<std::string,std::string>("her", "Herero"),
	std::make_pair<std::string,std::string>("hil", "Hiligaynon"),
	std::make_pair<std::string,std::string>("him", "Himachali languages; Western Pahari languages"),
	std::make_pair<std::string,std::string>("hin", "Hindi"),
	std::make_pair<std::string,std::string>("hit", "Hittite"),
	std::make_pair<std::string,std::string>("hmn", "Hmong; Mong"),
	std::make_pair<std::string,std::string>("hmo", "Hiri Motu"),
	std::make_pair<std::string,std::string>("hrv", "Croatian"),
	std::make_pair<std::string,std::string>("hsb", "Upper Sorbian"),
	std::make_pair<std::string,std::string>("hun", "Hungarian"),
	std::make_pair<std::string,std::string>("hup", "Hupa"),
	std::make_pair<std::string,std::string>("iba", "Iban"),
	std::make_pair<std::string,std::string>("ibo", "Igbo"),
	std::make_pair<std::string,std::string>("ice", "Icelandic"),
	std::make_pair<std::string,std::string>("isl", "Icelandic"),
	std::make_pair<std::string,std::string>("ido", "Ido"),
	std::make_pair<std::string,std::string>("iii", "Sichuan Yi; Nuosu"),
	std::make_pair<std::string,std::string>("ijo", "Ijo languages"),
	std::make_pair<std::string,std::string>("iku", "Inuktitut"),
	std::make_pair<std::string,std::string>("ile", "Interlingue; Occidental"),
	std::make_pair<std::string,std::string>("ilo", "Iloko"),
	std::make_pair<std::string,std::string>("ina", "Interlingua (International Auxiliary Language Association)"),
	std::make_pair<std::string,std::string>("inc", "Indic languages"),
	std::make_pair<std::string,std::string>("ind", "Indonesian"),
	std::make_pair<std::string,std::string>("ine", "Indo-European languages"),
	std::make_pair<std::string,std::string>("inh", "Ingush"),
	std::make_pair<std::string,std::string>("ipk", "Inupiaq"),
	std::make_pair<std::string,std::string>("ira", "Iranian languages"),
	std::make_pair<std::string,std::string>("iro", "Iroquoian languages"),
	std::make_pair<std::string,std::string>("ita", "Italian"),
	std::make_pair<std::string,std::string>("jav", "Javanese"),
	std::make_pair<std::string,std::string>("jbo", "Lojban"),
	std::make_pair<std::string,std::string>("jpn", "Japanese"),
	std::make_pair<std::string,std::string>("jpr", "Judeo-Persian"),
	std::make_pair<std::string,std::string>("jrb", "Judeo-Arabic"),
	std::make_pair<std::string,std::string>("kaa", "Kara-Kalpak"),
	std::make_pair<std::string,std::string>("kab", "Kabyle"),
	std::make_pair<std::string,std::string>("kac", "Kachin; Jingpho"),
	std::make_pair<std::string,std::string>("kal", "Kalaallisut; Greenlandic"),
	std::make_pair<std::string,std::string>("kam", "Kamba"),
	std::make_pair<std::string,std::string>("kan", "Kannada"),
	std::make_pair<std::string,std::string>("kar", "Karen languages"),
	std::make_pair<std::string,std::string>("kas", "Kashmiri"),
	std::make_pair<std::string,std::string>("kat", "Georgian"),
	std::make_pair<std::string,std::string>("geo", "Georgian"),
	std::make_pair<std::string,std::string>("kau", "Kanuri"),
	std::make_pair<std::string,std::string>("kaw", "Kawi"),
	std::make_pair<std::string,std::string>("kaz", "Kazakh"),
	std::make_pair<std::string,std::string>("kbd", "Kabardian"),
	std::make_pair<std::string,std::string>("kha", "Khasi"),
	std::make_pair<std::string,std::string>("khi", "Khoisan languages"),
	std::make_pair<std::string,std::string>("khm", "Central Khmer"),
	std::make_pair<std::string,std::string>("kho", "Khotanese; Sakan"),
	std::make_pair<std::string,std::string>("kik", "Kikuyu; Gikuyu"),
	std::make_pair<std::string,std::string>("kin", "Kinyarwanda"),
	std::make_pair<std::string,std::string>("kir", "Kirghiz; Kyrgyz"),
	std::make_pair<std::string,std::string>("kmb", "Kimbundu"),
	std::make_pair<std::string,std::string>("kok", "Konkani"),
	std::make_pair<std::string,std::string>("kom", "Komi"),
	std::make_pair<std::string,std::string>("kon", "Kongo"),
	std::make_pair<std::string,std::string>("kor", "Korean"),
	std::make_pair<std::string,std::string>("kos", "Kosraean"),
	std::make_pair<std::string,std::string>("kpe", "Kpelle"),
	std::make_pair<std::string,std::string>("krc", "Karachay-Balkar"),
	std::make_pair<std::string,std::string>("krl", "Karelian"),
	std::make_pair<std::string,std::string>("kro", "Kru languages"),
	std::make_pair<std::string,std::string>("kru", "Kurukh"),
	std::make_pair<std::string,std::string>("kua", "Kuanyama; Kwanyama"),
	std::make_pair<std::string,std::string>("kum", "Kumyk"),
	std::make_pair<std::string,std::string>("kur", "Kurdish"),
	std::make_pair<std::string,std::string>("kut", "Kutenai"),
	std::make_pair<std::string,std::string>("lad", "Ladino"),
	std::make_pair<std::string,std::string>("lah", "Lahnda"),
	std::make_pair<std::string,std::string>("lam", "Lamba"),
	std::make_pair<std::string,std::string>("lao", "Lao"),
	std::make_pair<std::string,std::string>("lat", "Latin"),
	std::make_pair<std::string,std::string>("lav", "Latvian"),
	std::make_pair<std::string,std::string>("lez", "Lezghian"),
	std::make_pair<std::string,std::string>("lim", "Limburgan; Limburger; Limburgish"),
	std::make_pair<std::string,std::string>("lin", "Lingala"),
	std::make_pair<std::string,std::string>("lit", "Lithuanian"),
	std::make_pair<std::string,std::string>("lol", "Mongo"),
	std::make_pair<std::string,std::string>("loz", "Lozi"),
	std::make_pair<std::string,std::string>("ltz", "Luxembourgish; Letzeburgesch"),
	std::make_pair<std::string,std::string>("lua", "Luba-Lulua"),
	std::make_pair<std::string,std::string>("lub", "Luba-Katanga"),
	std::make_pair<std::string,std::string>("lug", "Ganda"),
	std::make_pair<std::string,std::string>("lui", "Luiseno"),
	std::make_pair<std::string,std::string>("lun", "Lunda"),
	std::make_pair<std::string,std::string>("luo", "Luo (Kenya and Tanzania)"),
	std::make_pair<std::string,std::string>("lus", "Lushai"),
	std::make_pair<std::string,std::string>("mac", "Macedonian"),
	std::make_pair<std::string,std::string>("mkd", "Macedonian"),
	std::make_pair<std::string,std::string>("mad", "Madurese"),
	std::make_pair<std::string,std::string>("mag", "Magahi"),
	std::make_pair<std::string,std::string>("mah", "Marshallese"),
	std::make_pair<std::string,std::string>("mai", "Maithili"),
	std::make_pair<std::string,std::string>("mak", "Makasar"),
	std::make_pair<std::string,std::string>("mal", "Malayalam"),
	std::make_pair<std::string,std::string>("man", "Mandingo"),
	std::make_pair<std::string,std::string>("mao", "Maori"),
	std::make_pair<std::string,std::string>("mri", "Maori"),
	std::make_pair<std::string,std::string>("map", "Austronesian languages"),
	std::make_pair<std::string,std::string>("mar", "Marathi"),
	std::make_pair<std::string,std::string>("mas", "Masai"),
	std::make_pair<std::string,std::string>("may", "Malay"),
	std::make_pair<std::string,std::string>("msa", "Malay"),
	std::make_pair<std::string,std::string>("mdf", "Moksha"),
	std::make_pair<std::string,std::string>("mdr", "Mandar"),
	std::make_pair<std::string,std::string>("men", "Mende"),
	std::make_pair<std::string,std::string>("mga", "Middle Irish (900-1200)"),
	std::make_pair<std::string,std::string>("mic", "Mi'kmaq; Micmac"),
	std::make_pair<std::string,std::string>("min", "Minangkabau"),
	std::make_pair<std::string,std::string>("mis", "Uncoded languages"),
	std::make_pair<std::string,std::string>("mkh", "Mon-Khmer languages"),
	std::make_pair<std::string,std::string>("mlg", "Malagasy"),
	std::make_pair<std::string,std::string>("mlt", "Maltese"),
	std::make_pair<std::string,std::string>("mnc", "Manchu"),
	std::make_pair<std::string,std::string>("mni", "Manipuri"),
	std::make_pair<std::string,std::string>("mno", "Manobo languages"),
	std::make_pair<std::string,std::string>("moh", "Mohawk"),
	std::make_pair<std::string,std::string>("mon", "Mongolian"),
	std::make_pair<std::string,std::string>("mos", "Mossi"),
	std::make_pair<std::string,std::string>("mri", "Maori"),
	std::make_pair<std::string,std::string>("mao", "Maori"),
	std::make_pair<std::string,std::string>("msa", "Malay"),
	std::make_pair<std::string,std::string>("may", "Malay"),
	std::make_pair<std::string,std::string>("mul", "Multiple languages"),
	std::make_pair<std::string,std::string>("mun", "Munda languages"),
	std::make_pair<std::string,std::string>("mus", "Creek"),
	std::make_pair<std::string,std::string>("mwl", "Mirandese"),
	std::make_pair<std::string,std::string>("mwr", "Marwari"),
	std::make_pair<std::string,std::string>("mya", "Burmese"),
	std::make_pair<std::string,std::string>("bur", "Burmese"),
	std::make_pair<std::string,std::string>("myn", "Mayan languages"),
	std::make_pair<std::string,std::string>("myv", "Erzya"),
	std::make_pair<std::string,std::string>("nah", "Nahuatl languages"),
	std::make_pair<std::string,std::string>("nai", "North American Indian languages"),
	std::make_pair<std::string,std::string>("nap", "Neapolitan"),
	std::make_pair<std::string,std::string>("nau", "Nauru"),
	std::make_pair<std::string,std::string>("nav", "Navajo; Navaho"),
	std::make_pair<std::string,std::string>("nbl", "Ndebele"),
	std::make_pair<std::string,std::string>("nde", "Ndebele"),
	std::make_pair<std::string,std::string>("ndo", "Ndonga"),
	std::make_pair<std::string,std::string>("nds", "Low German; Low Saxon"),
	std::make_pair<std::string,std::string>("nep", "Nepali"),
	std::make_pair<std::string,std::string>("new", "Nepal Bhasa; Newari"),
	std::make_pair<std::string,std::string>("nia", "Nias"),
	std::make_pair<std::string,std::string>("nic", "Niger-Kordofanian languages"),
	std::make_pair<std::string,std::string>("niu", "Niuean"),
	std::make_pair<std::string,std::string>("nld", "Dutch; Flemish"),
	std::make_pair<std::string,std::string>("dut", "Dutch; Flemish"),
	std::make_pair<std::string,std::string>("nno", "Norwegian Nynorsk; Nynorsk"),
	std::make_pair<std::string,std::string>("nob", "Bokmål"),
	std::make_pair<std::string,std::string>("nog", "Nogai"),
	std::make_pair<std::string,std::string>("non", "Old Norse"),
	std::make_pair<std::string,std::string>("nor", "Norwegian"),
	std::make_pair<std::string,std::string>("nqo", "N'Ko"),
	std::make_pair<std::string,std::string>("nso", "Pedi; Sepedi; Northern Sotho"),
	std::make_pair<std::string,std::string>("nub", "Nubian languages"),
	std::make_pair<std::string,std::string>("nwc", "Classical Newari; Old Newari; Classical Nepal Bhasa"),
	std::make_pair<std::string,std::string>("nya", "Chichewa; Chewa; Nyanja"),
	std::make_pair<std::string,std::string>("nym", "Nyamwezi"),
	std::make_pair<std::string,std::string>("nyn", "Nyankole"),
	std::make_pair<std::string,std::string>("nyo", "Nyoro"),
	std::make_pair<std::string,std::string>("nzi", "Nzima"),
	std::make_pair<std::string,std::string>("oci", "Occitan (post 1500); Provençal"),
	std::make_pair<std::string,std::string>("oji", "Ojibwa"),
	std::make_pair<std::string,std::string>("ori", "Oriya"),
	std::make_pair<std::string,std::string>("orm", "Oromo"),
	std::make_pair<std::string,std::string>("osa", "Osage"),
	std::make_pair<std::string,std::string>("oss", "Ossetian; Ossetic"),
	std::make_pair<std::string,std::string>("ota", "Ottoman Turkish (1500-1928)"),
	std::make_pair<std::string,std::string>("oto", "Otomian languages"),
	std::make_pair<std::string,std::string>("paa", "Papuan languages"),
	std::make_pair<std::string,std::string>("pag", "Pangasinan"),
	std::make_pair<std::string,std::string>("pal", "Pahlavi"),
	std::make_pair<std::string,std::string>("pam", "Pampanga; Kapampangan"),
	std::make_pair<std::string,std::string>("pan", "Panjabi; Punjabi"),
	std::make_pair<std::string,std::string>("pap", "Papiamento"),
	std::make_pair<std::string,std::string>("pau", "Palauan"),
	std::make_pair<std::string,std::string>("peo", "Old Persian (600-400 BC)"),
	std::make_pair<std::string,std::string>("per", "Persian"),
	std::make_pair<std::string,std::string>("phi", "Philippine languages"),
	std::make_pair<std::string,std::string>("phn", "Phoenician"),
	std::make_pair<std::string,std::string>("pli", "Pali"),
	std::make_pair<std::string,std::string>("pol", "Polish"),
	std::make_pair<std::string,std::string>("pon", "Pohnpeian"),
	std::make_pair<std::string,std::string>("por", "Portuguese"),
	std::make_pair<std::string,std::string>("pra", "Prakrit languages"),
	std::make_pair<std::string,std::string>("pro", "Old Provencal (to 1500); Old Occitan (to 1500)"),
	std::make_pair<std::string,std::string>("pus", "Pushto; Pashto"),
	std::make_pair<std::string,std::string>("que", "Quechua"),
	std::make_pair<std::string,std::string>("raj", "Rajasthani"),
	std::make_pair<std::string,std::string>("rap", "Rapanui"),
	std::make_pair<std::string,std::string>("rar", "Rarotongan; Cook Islands Maori"),
	std::make_pair<std::string,std::string>("roa", "Romance languages"),
	std::make_pair<std::string,std::string>("roh", "Romansh"),
	std::make_pair<std::string,std::string>("rom", "Romany"),
	std::make_pair<std::string,std::string>("ron", "Romanian; Moldavian; Moldovan"),
	std::make_pair<std::string,std::string>("rum", "Romanian; Moldavian; Moldovan"),
	std::make_pair<std::string,std::string>("run", "Rundi"),
	std::make_pair<std::string,std::string>("rup", "Aromanian; Arumanian; Macedo-Romanian"),
	std::make_pair<std::string,std::string>("rus", "Russian"),
	std::make_pair<std::string,std::string>("sad", "Sandawe"),
	std::make_pair<std::string,std::string>("sag", "Sango"),
	std::make_pair<std::string,std::string>("sah", "Yakut"),
	std::make_pair<std::string,std::string>("sai", "South American Indian Languages"),
	std::make_pair<std::string,std::string>("sal", "Salishan languages"),
	std::make_pair<std::string,std::string>("sam", "Samaritan Aramaic"),
	std::make_pair<std::string,std::string>("san", "Sanskrit"),
	std::make_pair<std::string,std::string>("sas", "Sasak"),
	std::make_pair<std::string,std::string>("sat", "Santali"),
	std::make_pair<std::string,std::string>("scn", "Sicilian"),
	std::make_pair<std::string,std::string>("sco", "Scots"),
	std::make_pair<std::string,std::string>("sel", "Selkup"),
	std::make_pair<std::string,std::string>("sem", "Semitic languages"),
	std::make_pair<std::string,std::string>("sga", "Old Irish (to 900)"),
	std::make_pair<std::string,std::string>("sgn", "Sign languages"),
	std::make_pair<std::string,std::string>("shn", "Shan"),
	std::make_pair<std::string,std::string>("sid", "Sidamo"),
	std::make_pair<std::string,std::string>("sin", "Sinhala; Sinhalese"),
	std::make_pair<std::string,std::string>("slo", "Slovak"),
	std::make_pair<std::string,std::string>("slk", "Slovak"),
	std::make_pair<std::string,std::string>("slv", "Slovenian"),
	std::make_pair<std::string,std::string>("sma", "Southern Sami"),
	std::make_pair<std::string,std::string>("sme", "Northern Sami"),
	std::make_pair<std::string,std::string>("smi", "Sami languages"),
	std::make_pair<std::string,std::string>("smj", "Lule Sami"),
	std::make_pair<std::string,std::string>("smn", "Inari Sami"),
	std::make_pair<std::string,std::string>("smo", "Samoan"),
	std::make_pair<std::string,std::string>("sms", "Skolt Sami"),
	std::make_pair<std::string,std::string>("sna", "Shona"),
	std::make_pair<std::string,std::string>("snd", "Sindhi"),
	std::make_pair<std::string,std::string>("snk", "Soninke"),
	std::make_pair<std::string,std::string>("sog", "Sogdian"),
	std::make_pair<std::string,std::string>("som", "Somali"),
	std::make_pair<std::string,std::string>("son", "Songhai languages"),
	std::make_pair<std::string,std::string>("sot", "Sotho"),
	std::make_pair<std::string,std::string>("spa", "Spanish; Castilian"),
	std::make_pair<std::string,std::string>("sqi", "Albanian"),
	std::make_pair<std::string,std::string>("alb", "Albanian"),
	std::make_pair<std::string,std::string>("srd", "Sardinian"),
	std::make_pair<std::string,std::string>("srn", "Sranan Tongo"),
	std::make_pair<std::string,std::string>("srp", "Serbian"),
	std::make_pair<std::string,std::string>("srr", "Serer"),
	std::make_pair<std::string,std::string>("ssa", "Nilo-Saharan languages"),
	std::make_pair<std::string,std::string>("ssw", "Swati"),
	std::make_pair<std::string,std::string>("suk", "Sukuma"),
	std::make_pair<std::string,std::string>("sun", "Sundanese"),
	std::make_pair<std::string,std::string>("sus", "Susu"),
	std::make_pair<std::string,std::string>("sux", "Sumerian"),
	std::make_pair<std::string,std::string>("swa", "Swahili"),
	std::make_pair<std::string,std::string>("swe", "Swedish"),
	std::make_pair<std::string,std::string>("syc", "Classical Syriac"),
	std::make_pair<std::string,std::string>("syr", "Syriac"),
	std::make_pair<std::string,std::string>("tah", "Tahitian"),
	std::make_pair<std::string,std::string>("tai", "Tai languages"),
	std::make_pair<std::string,std::string>("tam", "Tamil"),
	std::make_pair<std::string,std::string>("tat", "Tatar"),
	std::make_pair<std::string,std::string>("tel", "Telugu"),
	std::make_pair<std::string,std::string>("tem", "Timne"),
	std::make_pair<std::string,std::string>("ter", "Tereno"),
	std::make_pair<std::string,std::string>("tet", "Tetum"),
	std::make_pair<std::string,std::string>("tgk", "Tajik"),
	std::make_pair<std::string,std::string>("tgl", "Tagalog"),
	std::make_pair<std::string,std::string>("tha", "Thai"),
	std::make_pair<std::string,std::string>("tib", "Tibetan"),
	std::make_pair<std::string,std::string>("bod", "Tibetan"),
	std::make_pair<std::string,std::string>("tig", "Tigre"),
	std::make_pair<std::string,std::string>("tir", "Tigrinya"),
	std::make_pair<std::string,std::string>("tiv", "Tiv"),
	std::make_pair<std::string,std::string>("tkl", "Tokelau"),
	std::make_pair<std::string,std::string>("tlh", "Klingon; tlhIngan-Hol"),
	std::make_pair<std::string,std::string>("tli", "Tlingit"),
	std::make_pair<std::string,std::string>("tmh", "Tamashek"),
	std::make_pair<std::string,std::string>("tog", "Tonga (Nyasa)"),
	std::make_pair<std::string,std::string>("ton", "Tonga (Tonga Islands)"),
	std::make_pair<std::string,std::string>("tpi", "Tok Pisin"),
	std::make_pair<std::string,std::string>("tsi", "Tsimshian"),
	std::make_pair<std::string,std::string>("tsn", "Tswana"),
	std::make_pair<std::string,std::string>("tso", "Tsonga"),
	std::make_pair<std::string,std::string>("tuk", "Turkmen"),
	std::make_pair<std::string,std::string>("tum", "Tumbuka"),
	std::make_pair<std::string,std::string>("tup", "Tupi languages"),
	std::make_pair<std::string,std::string>("tur", "Turkish"),
	std::make_pair<std::string,std::string>("tut", "Altaic languages"),
	std::make_pair<std::string,std::string>("tvl", "Tuvalua"),
	std::make_pair<std::string,std::string>("twi", "Twi"),
	std::make_pair<std::string,std::string>("tyv", "Tuvinian"),
	std::make_pair<std::string,std::string>("udm", "Udmurt"),
	std::make_pair<std::string,std::string>("uga", "Ugaritic"),
	std::make_pair<std::string,std::string>("uig", "Uighur; Uyghur"),
	std::make_pair<std::string,std::string>("ukr", "Ukrainian"),
	std::make_pair<std::string,std::string>("umb", "Umbundu"),
	std::make_pair<std::string,std::string>("und", "Undetermined"),
	std::make_pair<std::string,std::string>("urd", "Urdu"),
	std::make_pair<std::string,std::string>("uzb", "Uzbek"),
	std::make_pair<std::string,std::string>("vai", "Vai"),
	std::make_pair<std::string,std::string>("ven", "Venda"),
	std::make_pair<std::string,std::string>("vie", "Vietnamese"),
	std::make_pair<std::string,std::string>("vol", "Volapük"),
	std::make_pair<std::string,std::string>("vot", "Votic"),
	std::make_pair<std::string,std::string>("wak", "Wakashan languages"),
	std::make_pair<std::string,std::string>("wal", "Wolaitta; Wolaytta"),
	std::make_pair<std::string,std::string>("war", "Waray"),
	std::make_pair<std::string,std::string>("was", "Washo"),
	std::make_pair<std::string,std::string>("wel", "Welsh"),
	std::make_pair<std::string,std::string>("cym", "Welsh"),
	std::make_pair<std::string,std::string>("wen", "Sorbian languages"),
	std::make_pair<std::string,std::string>("wln", "Walloon"),
	std::make_pair<std::string,std::string>("wol", "Wolof"),
	std::make_pair<std::string,std::string>("xal", "Kalmyk; Oirat"),
	std::make_pair<std::string,std::string>("xho", "Xhosa"),
	std::make_pair<std::string,std::string>("yao", "Yao"),
	std::make_pair<std::string,std::string>("yap", "Yapese"),
	std::make_pair<std::string,std::string>("yid", "Yiddish"),
	std::make_pair<std::string,std::string>("yor", "Yoruba"),
	std::make_pair<std::string,std::string>("ypk", "Yupik languages"),
	std::make_pair<std::string,std::string>("zap", "Zapotec"),
	std::make_pair<std::string,std::string>("zbl", "Blissymbols; Blissymbolics; Bliss"),
	std::make_pair<std::string,std::string>("zen", "Zenaga"),
	std::make_pair<std::string,std::string>("zgh", "Standard Moroccan Tamazight"),
	std::make_pair<std::string,std::string>("zha", "Zhuang; Chuang"),
	std::make_pair<std::string,std::string>("zho", "Chinese"),
	std::make_pair<std::string,std::string>("chi", "Chinese"),
	std::make_pair<std::string,std::string>("znd", "Zande languages"),
	std::make_pair<std::string,std::string>("zul", "Zulu"),
	std::make_pair<std::string,std::string>("zun", "Zuni"),
	std::make_pair<std::string,std::string>("zxx", "No linguistic content; Not applicable"),
	std::make_pair<std::string,std::string>("zza", "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki"),
};

namespace ISO639_2 {

	std::string const &language(std::string const &code) {
		std::map<std::string,std::string>::const_iterator it=langs.find(code);
		if(it != langs.end())
			return it->second;
		return code; 
	}

}
